name: Deploy Kanban Board to GitHub Pages

on:
  push:
    branches:
      - "main" # change to your main branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - id: build-publish
      uses: bitovi/github-actions-angular-to-github-pages@v1.0.0
      with:
        path: dist/${{ github.event.repository.name }}/browser
        build_command: npm run build -- --base-href=/${{ github.event.repository.name }}/
